baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Know That You Anointed'
theme = 'hugo-PaperMod'
description = 'A blog where hip hop intersects with Christian spirituality'

[params]
env = 'production' # to enable google analytics, opengraph, twitter-cards and schema.
description = 'A blog where hip hop intersects with Christian spirituality'
author = 'Femi'

assets.favicon = "assets/favicon.ico"

# defaultTheme = 'auto'
# disableThemeToggle = true
ShowShareButtons = false
ShowReadingTime = true
disableSpecial1stPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList= true
ShowAllPagesInArchive = true
ShowPageNums = true
# ShowToc = true
# comments = false


homeInfoParams.title = "A blog on the intersection between \n Christian spirituality and hip hop"

homeInfoParams.content = '''
### by Femi "Athanasios" Olutade

* [About me](www.example.com)
* About blog
<b>
<p>This is a sample description.</p>
anything
'''
